version: "3.9"
services:
    postgres:
        build: database
        ports:
            - 2003:2003
        volumes:
            - gces-database:/var/lib/postgresql/data
    backend:
        build: library_back
        ports:
            - 8000:8000
        env_file:
            - ./library_back/.env
        depends_on:
            - postgres
volumes:
    gces-database:
