version: "3.9"
services:
    postgres:
        build: database
        ports:
            - 2003:2003
        volumes:
            - gces-database:/var/lib/postgresql/data
    backend:
        build: library_back
        ports:
            - 8000:8000
        env_file:
            - ./library_back/.env
        depends_on:
            - postgres
    frontend:
        build: library_front
        working_dir: /app/library_front
        ports:
            - 3002:3002
        depends_on:
            - postgres
            - backend
    nginx:
        build: nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - frontend
        links:
            - frontend
volumes:
    gces-database:
